sono_project/QuantoDormi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.calculadora)
]

sono_project/Recomendar/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.formularioRecomendacao)
]

sono_project/Sonia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("treino/", views.ListarTreinamento.as_view(), name="sonia_train_index"),
    path("treino/create", views.CriarTreinamento.as_view(), name="sonia_train_create")
]

sono_project/TIRescue/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='tirescue-home'),
    path('informar/', views.informar_problema, name='tirescue-info-problema'),
    path('deletar/<int:problema_id>/', views.deletar_problema, name='tirescue-del-problema'),
]

sono_project/sonoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('adm/', admin.site.urls),
    path('quantodormi/', include('QuantoDormi.urls')),
    path('ti/', include('TIRescue.urls')),
    path('sonia/', include('Sonia.urls'), name="sonia"),
    path('rec/', include('Recomendar.urls'))
]

sono_project/QuantoDormi/models.py
from django.db import models

# Create your models here.

sono_project/Recomendar/models.py
from django.db import models

# Create your models here.
class DadosDePessoasModel(models.Model):
    TIPO_DO_MODELO = [
        ("NS", "Não Sabe"),
        ("EF", "Extra Firme"),
        ("F", "Firme"),
        ("I", "Intermediário"),
        ("M", "Macio")
    ]

    DOENCA_CHOICES = [
        ("S", "Sim"),
        ("N", "Não")
    ]

    nome = models.CharField(max_length=150)
    telefone = models.CharField(max_length=13, null=True)
    email =  models.CharField(max_length=150,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    idade = models.IntegerField()
    altura = models.IntegerField()
    modelo_anterior = models.CharField(
        max_length=2,
        choices=TIPO_DO_MODELO
    )
    quantos_acompanhantes = models.IntegerField()
    tem_doenca = models.CharField(
        max_length=1,
        choices=DOENCA_CHOICES,
        blank=True,
    )

    peso = models.CharField(max_length=80)

    def __str__(self):
        return self.nome + " | " + str(self.created_at)


class ModeloDeColchoes(models.Model):
    TIPO_DO_MODELO = [
        ("EF", "Extra Firme"),
        ("F", "Firme"),
        ("I", "Intermediário"),
        ("M", "Macio")
    ]
    nome = models.CharField(max_length=100)
    nivel_de_maciez = models.IntegerField()
    categoria = models.CharField(
        max_length=60,
        choices=TIPO_DO_MODELO
    )

sono_project/Sonia/models.py
from django.db import models

# Create your models here.
class Treino(models.Model):

    resultado = models.CharField(max_length=100)
    data_criacao = models.DateTimeField(verbose_name="Data de Criação",auto_created=True)
    imc = models.FloatField(verbose_name="IMC")
    altura = models.FloatField()
    peso = models.FloatField()
    doenca = models.BooleanField(verbose_name="Possui Doença Relevante")

    class Meta:
        verbose_name = "Dado de treino da Sonia"
        verbose_name_plural = "Dados de treino da Sonia"

    def __str__(self):
        return self.name

sono_project/TIRescue/models.py
from django.db import models

# Create your models here.
class Problema(models.Model):
    author = models.CharField(max_length=150)
    titulo = models.CharField(max_length=300)
    descricao = models.TextField()

sono_project/Recomendar/forms.py
from django import forms

class FormularioRecomendacaoForm(forms.Form):
    nome = forms.CharField(label="Qual é o seu nome?")
    telefone = forms.CharField(max_length=13, required=False)
    email = forms.CharField(required=False)
    
    idade = forms.IntegerField()
    altura = forms.IntegerField()
    modelo_anterior = forms.ChoiceField(
        choices=[
            ("NS", "Não Sabe"),
            ("EF", "Extra Firme"),
            ("F", "Firme"),
            ("I", "Intermediário"),
            ("M", "Macio")
        ], 
        label="Qual tipo de colchão você usava?"
    )

    quantos_acompanhantes = forms.IntegerField(min_value=0)
    
    tem_doenca = forms.ChoiceField(
        choices=[
            ("S","Sim"),
            ("N","Não")
        ],
        label="Você tem alguma doença de coluna?", 
    )

    peso = forms.CharField(required=True)

sono_project/QuantoDormi/views.py
from django.shortcuts import render

# Create your views here.
def calculadora(request):
    return render(request, "quantodormi/calculadora.html")

sono_project/Recomendar/views.py
from django.shortcuts import render
from .forms import FormularioRecomendacaoForm
from .models import DadosDePessoasModel

# Create your views here.
def formularioRecomendacao(request):
    if request.method == "POST":
        form = FormularioRecomendacaoForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            
            # Aqui você deve passar os campos corretamente, usando o dicionário `data`
            dadosdepessoal = DadosDePessoasModel(
                nome=data['nome'],
                telefone=data['telefone'],
                email=data['email'],
                altura=data['altura'],
                idade=data['idade'],
                modelo_anterior=data['modelo_anterior'],
                quantos_acompanhantes=data['quantos_acompanhantes'],
                tem_doenca=data['tem_doenca'],
                peso=data['peso']
            )
            
            dadosdepessoal.save()
            
            return render(request, "recomendar/listar_recomendacoes.html")
        
    return render(request, "recomendar/formulario_cliente.html")


def listarTreino(request):
    pass

def adicionarTreino(request):
    if request.method == "POST":
        pass
    
    return render(request, "recomendar/formulario_cliente.html")

sono_project/Sonia/views.py
from django.views.generic import View

from django.shortcuts import render
from .models import Treino
from . import utils


class ListarTreinamento(View):
    def get(self, request):
        treinos = Treino.objects.all()
        return render(request, "sonia/treinamento/index.html", {"treinos":treinos})
    
class CriarTreinamento(View):
    def get(self, request):
        return render(request, "sonia/treinamento/create.html")

sono_project/TIRescue/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Problema

# View da página inicial
def home(request):
    problemas = Problema.objects.all()
    return render(request, "tirescue/home.html", {"problemas": problemas})

# View para informar um problema
def informar_problema(request):
    if request.method == "POST":
        dados_do_problema = request.POST
        problemas = []

        # Adiciona os problemas selecionados à lista
        if dados_do_problema.get("problema_inexistencia"):
            problemas.append("non ecziste")
        if dados_do_problema.get("problema_duplicado"):
            problemas.append("doppelganger")
        if dados_do_problema.get("problema_preco"):
            problemas.append("preço")
        if dados_do_problema.get("problema_nome"):
            problemas.append("nome")
        if dados_do_problema.get("problema_marca"):
            problemas.append("marca")
        if dados_do_problema.get("problema_ncm"):
            problemas.append("CHIANCA MALDITO (NCM)")
        if dados_do_problema.get("outro_problema"):
            problemas.append(dados_do_problema.get("outro_problema"))

        # Concatena os problemas em uma string
        descricao = ", ".join(problemas)

        # Cria e salva o problema
        problema = Problema(
            author=dados_do_problema.get("author"),
            titulo=dados_do_problema.get("titulo"),
            descricao=descricao
        )
        problema.save()

        return redirect("tirescue-home")
    return render(request, "tirescue/informar_problema.html")

# View para deletar um problema
def deletar_problema(request, problema_id):
    problema = get_object_or_404(Problema, id=problema_id)
    
    if request.method == "POST":
        problema.delete()
        return redirect("tirescue-home")

    return render(request, "tirescue/confirmar_delecao.html", {"problema": problema})

sono_project/QuantoDormi/templates/quantodormi/calculadora.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
    <title>Calculadora de Sono</title>
    <style>
        html, body {
            min-height: 100vh;
        }

        body {
            transition: background-color 0.3s ease;
        }

        main.container {
            max-width: 500px;
            padding: 20px;
            border-radius: 8px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        .result {
            text-align: center;
            margin-top: 20px;
            font-size: 1.3rem;
            display: none;
        }

        /* Ajuste das cores para os temas claro e escuro */
        @media (prefers-color-scheme: dark) {
            body {
                background-color: #1e1e1e;
            }
        }

        @media (prefers-color-scheme: light) {
            body {
                background-color: #f5f5f5;
            }
        }
    </style>
</head>
<body>
    <header class="container">
        <nav>
            <ul>
              <li><strong>Sono Colchões</strong></li>
            </ul>
            <ul>
              <li><a href="#">Em desenvolvimento</a></li>
            </ul>
          </nav>
    </header>
    <main class="container">
        <h1>Calculadora de Sono</h1>
        
        <form id="sleepForm">
            <fieldset class="grid">
                <label>
                    Hora que você foi dormir:
                    <input
                        type="time"
                        name="iniciodosono"
                        id="iniciodosono"
                        required
                    />
                </label>

                <label>
                    Hora que você acordou:
                    <input
                        type="time"
                        name="fimdosono"
                        id="fimdosono"
                        required
                    />
                </label>
            </fieldset>
            <button type="submit" class="primary">Calcular Horas de Sono</button>
        </form>

        <div class="result" id="result">
            Você dormiu <span id="sleepHours"></span> horas e <span id="sleepMinutes"></span> minutos.
            <p><small id="sleepComment">sasasa</small></p>
        </div>
    </main>

    <script>
        document.getElementById('sleepForm').addEventListener('submit', function(event) {
            event.preventDefault();
            
            const startTime = document.getElementById('iniciodosono').value;
            const endTime = document.getElementById('fimdosono').value;

            if (!startTime || !endTime) return;

            // Converte os horários em minutos desde a meia-noite
            const start = new Date(`1970-01-01T${startTime}:00`);
            const end = new Date(`1970-01-01T${endTime}:00`);

            let diff = (end - start) / (1000 * 60); // Diferença em minutos

            // Se acordar no dia seguinte
            if (diff < 0) {
                diff += 24 * 60;
            }

            const hours = Math.floor(diff / 60);
            const minutes = diff % 60;

            document.getElementById('sleepHours').textContent = hours;
            document.getElementById('sleepMinutes').textContent = minutes;
            var comment = document.getElementById('sleepComment');

            if (hours >= 10) {
                comment.innerText = "Exagerou, hein? Tudo em excesso faz mal! Que tal acordar mais cedo e aproveitar a energia extra com um colchão Ecoflex? Você merece o melhor descanso!"
            } else if (hours >= 9) {
                comment.innerText = "Está na hora de uma soneca extra! Mas não se esqueça, com um colchão Ecoflex, cada noite é uma festa de conforto!"
            } else if (hours === 8) {
                comment.innerText = "Você está mandando muito bem! Mas para transformar cada noite em um sonho perfeito, conheça os colchões Ecoflex da Sono Colchões!"
            } else if (hours === 7) {
                comment.innerText = "Está quase lá! Para uma experiência de sono que supera todas as expectativas, venha conferir os colchões Ecoflex na Sono Colchões!"
            } else if (hours === 6) {
                comment.innerText = "Pode ser que seu colchão não esteja no nível Ecoflex! Experimente um novo padrão de conforto com os produtos da Sono Colchões."
            } else if (hours >= 5) {
                comment.innerText = "Dormir pouco? Seu corpo merece mais! Venha descobrir como um colchão Ecoflex da Sono Colchões pode transformar suas noites em um verdadeiro descanso."
            }

            document.getElementById('result').style.display = 'block';
        });
    </script>
</body>
</html>

sono_project/Recomendar/templates/recomendar/formulario_cliente.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
</head>
<style>
    #maincontainer {

        max-width: 500px;
    }
    fieldset.grupode2 {
        display: grid;
        grid-template-columns: 50% 50%;
        gap: 0.3rem;
        margin: 0px;
    }
</style>

<body>
    <header class="container">
        <nav>
            <ul>
                <li>Sono Colchões</li>
            </ul>
            <ul>
                <li>
                    <a href="">Bioimpedancia</a>
                </li>
            </ul>
        </nav>
    </header>
    <div id="maincontainer" class="container">
        <form method="post">
            {% csrf_token %}
            <label>Qual é o seu nome?
                <input type="text" name="nome" required id="id_nome" maxlength="150">
            </label>

            <label>Qual é o seu número de telefone (apenas números)?
                <input type="tel" name="telefone" required id="id_telefone" maxlength="13">
            </label>

            <label>Qual é o seu email?
                <input type="email" name="email" required id="id_email" maxlength="150">
            </label>

            <label>Qual tipo de colchão você usava?
                <select name="modelo_anterior" id="id_modelo_anterior">
                    <option value="NS">Não Sabe</option>
                    <option value="EF">Extra Firme</option>
                    <option value="F">Firme</option>
                    <option value="I">Intermediário</option>
                    <option value="M">Macio</option>
                </select>
            </label>
        
            <fieldset class="grupode2">
                <label>Quantos centrimetros de altura você tem? (cm):
                    <input type="number" name="altura" required id="id_altura" max="250" min="50">
                </label>
                <label>Quantos anos de idade você tem?
                    <input type="number" name="idade" required id="id_idade" max="110">
                </label>
            </fieldset>
        
            <label>Você tem alguma doença de coluna?
                <select name="tem_doenca" id="id_tem_doenca">
                    <option value="S">Sim</option>
                    <option value="N">Não</option>
                </select>
            </label>

            <label>Quantas pessoas além de você iram dormir no colchão? <br> <output id="output_quantos_acompanhantes">0</output> pessoas exceto eu!
                <input type="range" name="quantos_acompanhantes" id="id_quantos_acompanhantes" max="3" min="0" value="0"
                    oninput="output_quantos_acompanhantes.textContent = this.value;">
            </label>

            <label>Informe os pesos separado por ";" em ordem esquerda cima para direita baixo.
                <textarea name="peso" id="id_peso" placeholder="35.0;20.0;20.0;50.0;30.0;30.0"></textarea>
            </label>
            
            <button type="submit">Obter Recomendação</button>
        </form>        
    </div>
</body>
</html>

sono_project/Recomendar/templates/recomendar/listar_recomendacoes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
</head>
<style>
    #maincontainer {

        max-width: 500px;
    }
</style>
<body>
    <header class="container">
        <nav>
            <ul>
                <li>Sono Colchões</li>
            </ul>
            <ul>
                <li>
                    <a href="">Bioimpedancia</a>
                </li>
            </ul>
        </nav>
    </header>
    <div id="maincontainer" class="container">
        Tela exibição de Recomendações
    </div>
</body>
</html>

sono_project/Sonia/templates/sonia/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <title>Sonia - Sono MTF Mu-4</title>
</head>
<body>
    <nav>
        <a href="#" class="brand">
            <img class="logo" src="{% static 'img/logo.jpg' %}" />
            <span>SONO <small>MTF Mu-4</small></span>
        </a>

        <!-- responsive-->
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button">&#9776;</label>

        <div class="menu">
            <a href="#" class="pseudo button icon-picture">Demo</a>
            <a href="#" class="pseudo button icon-puzzle">Treinamento</a>
            <a href="#" class="button icon-puzzle">Sonia</a>
        </div>
    </nav>
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <footer>
        <p>Só Colchões © 2024 - Todos os direitos reservados</p>
        <p>Feito por quem  ❤️  dormir</p>
    </footer>
</body>
</html>

sono_project/Sonia/templates/sonia/treinamento/create.html
{% extends "sonia/base.html" %}

sono_project/Sonia/templates/sonia/treinamento/index.html
{% extends "sonia/base.html" %}
{% block main %}
<h1 style="text-align: center; width: 100%;color:skyblue">Olá Tia Sara!</h1>
{% endblock %}

sono_project/TIRescue/templates/tirescue/confirmar_delecao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DELETAR PROBLEMA - TI-Rescue!!</title>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
</head>
<style>
    :root {
        --pico-color:snow !important;
    }

    body {
        background-color: #f55;
        color: snow !important;
        min-height: 100vh;
    }
    #maincontainer {
        max-width: 500px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    h1 {
        text-align: center;
        color: snow !important;
    }
    button {
        background-color: yellow !important;
        border-color: yellow !important;
        color: black !important;
    }
    a {
        color: yellow !important;
    }
</style>
<body>
    <header class="container">
        <nav>
            <ul>
                <li>Sono Colchões -TI Rescue</li>
            </ul>
            <ul>
                <li>
                    <a href="{% url 'tirescue-home' %}">Voltar</a>
                </li>
            </ul>
        </nav>
    </header>
    <div id="maincontainer" class="container">
        <form method="post">
            {% csrf_token %}
            <h1>Tem certeza que deseja deletar</h1>
            <p>{{ problema.titulo }} feito por {{ problema.author }}</p>
            <button type="submit">Sim</button>
        </form>
    </div>
</body>
</html>

sono_project/TIRescue/templates/tirescue/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TI-Rescue!!</title>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
</head>
<style>

</style>
<body>
    <header class="container">
        <nav>
            <ul>
                <li>Sono Colchões</li>
            </ul>
            <ul>
                <li>
                    <a href="{% url 'tirescue-info-problema' %}">Informar Problema</a>
                </li>
            </ul>
        </nav>
    </header>
    <div id="maincontainer" class="container">
        <section>
            <label>Terminal de Comando
                <input type="text" placeholder="Se você não sabe para que serve, não mexa">
            </label>
            <button>Enviar Comando</button>
        </section>
        <section>
            <h2>Produtos com Problemas</h2>
            {% if problemas %}
                <table>
                    <thead>
                        <td>Titulo</td>
                        <td>Author</td>
                        <td>Problemas</td>
                    </thead>
                    <tbody>
                        {% for problema in problemas %}
                        <tr>
                            <td>{{ problema.titulo }}</td>
                            <td><small>{{ problema.author }}</small></td>
                            <td>{{ problema.descricao }}</td>
                            <td><a href="{% url 'tirescue-del-problema' problema_id=problema.id %}">Deletar</a></td>                   
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Por enquanto sem problemas, YAY!!</p>
            {% endif %}
        </section>
    </div>
</body>
</html>

sono_project/TIRescue/templates/tirescue/informar_problema.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TI-Rescue!!</title>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
</head>
<style>
    #maincontainer {

        max-width: 500px;
    }
    fieldset.grupode2 {
        display: grid;
        grid-template-columns: 50% 50%;
        gap: 0.3rem;
        margin: 0px;
    }
</style>
<body>
    <header class="container">
        <nav>
            <ul>
                <li>Sono Colchões - TI Rescue</li>
            </ul>
            <ul>
                <li>
                    <a href="">Bioimpedancia</a>
                </li>
            </ul>
        </nav>
    </header>
    <div id="maincontainer" class="container">
        <form method="POST">
            {% csrf_token %}
            <h2>Reporta um Problema</h2>
            <label>Qual é o seu nome?
                <input type="text" name="author" required id="id_author" maxlength="150" placeholder="Nome">
            </label>
        
            <label>Nome do produto com problema
                <input type="text" name="titulo" required maxlength="300" placeholder="BASE SOFTFLEX BAÚ - 138x188 - CORINO BRANCO">
            </label>
        
            <h3>Onde está o problema?</h3>
            <fieldset>
                <label>
                    <input type="checkbox" name="problema_inexistencia">
                    <span class="checkable">Inexistência</span>
                </label>
                <label>
                    <input type="checkbox" name="problema_duplicado">
                    <span class="checkable">Duplicado</span>
                </label>
                <label>
                    <input type="checkbox" name="problema_preco">
                    <span class="checkable">Preço</span>
                </label>
                <label>
                    <input type="checkbox" name="problema_nome">
                    <span class="checkable">Nome do produto</span>
                </label>
                <label>
                    <input type="checkbox" name="problema_marca">
                    <span class="checkable">Marca</span>
                </label>
                <label>
                    <input type="checkbox" name="problema_ncm">
                    <span class="checkable">NCM ou Código CEST (geralmente se não conseguir gerar nota fiscal esse é o motivo)</span>
                </label>
                <input type="text" placeholder="Outro problema que não está na lista" name="outro_problema">
            </fieldset>
            
            <button type="submit">Enviar Problema</button>
        </form>        
    </div>
</body>
</html>